# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
net.minecraftforge.gradle.merge-source-sets=true

# Release line selected when no -Pmc_profile override is provided.
default_mc_profile=1.16.5

# Mod properties
mod_id=safra
mod_name=Safra
mod_version=1.0-SNAPSHOT
mod_license=LicenseRef-Safra-Source-Available-1.0
mod_description=Play Minecraft with your friend for free and without limits, no server or unnecessary setup required.
maven_group=org.developerkubilay
archives_base_name=Safra

# Fabric properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.16.5
yarn_mappings=1.16.5+build.10
loader_version=0.16.10
fabric_version=0.42.0+1.16

minecraft_version_range=[1.16.5]
loader_version_range=[1,)

# Forge properties
forge_version=36.2.39
forge_mappings=20210309-1.16.5
forge_version_range=[36,)
forge_loader_version_range=[36,)
forge_minecraft_version_range=[1.16.5]

# Optional compat properties
voicechat_api_version=2.6.13
