# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.10.7-hotspot
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=C:/Program Files/Eclipse Adoptium/jdk-21.0.10.7-hotspot
net.minecraftforge.gradle.merge-source-sets=true

# Release line selected when no -Pmc_profile override is provided.
default_mc_profile=1.20.5-1.20.6

# Mod properties
mod_id=safra
mod_name=Safra
base_minecraft_version=1.20.6
mod_version=1.0-SNAPSHOT
mod_license=LicenseRef-Safra-Source-Available-1.0
mod_description=Play Minecraft with your friend for free and without limits, no server or unnecessary setup required.
maven_group=org.developerkubilay
archives_base_name=Safra

# Fabric properties
# check these on https://modmuss50.me/fabric.html
fabric_minecraft_version=1.20.6
fabric_mod_minecraft_version=1.20.6
minecraft_version=1.20.6
yarn_mappings=1.20.6+build.3
loader_version=0.15.11
fabric_version=0.100.8+1.20.6

# NeoForge properties
enable_neoforge=true
minecraft_version_range=[1.20.5,1.20.7)
neo_version=20.6.137
neo_version_range=[20.5.21-beta,)
loader_version_range=[1,)

# Forge properties
forge_version=50.2.8
forge_version_range=[50,)
forge_loader_version_range=[50,)
forge_minecraft_version_range=[1.20.5,1.20.7)

# Optional compat properties
voicechat_api_version=2.6.13
