pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        gradlePluginPortal()
    }
}

rootProject.name = 'Safra'

include 'common'
if (!gradle.startParameter.projectProperties.containsKey('forgeOnly')) {
    include 'fabric'
}
if (!gradle.startParameter.projectProperties.containsKey('fabricOnly')) {
    include 'forge'
}
